// ============================================================
// THE WARRIORS — roster + profile data
// PLACEHOLDER seed data ported verbatim from the prototype
// (warriors.jsx). Jason replaces coaches / rosters / stats later.
// ============================================================

export const BADGES = [
  { name: 'Christian Character', img: '/badges/christian-character-final.png', desc: 'Glorify God. Leadership.' },
  { name: 'Shooting',      img: '/badges/shooting.png',      desc: 'Pure. Accurate. Deadly.' },
  { name: 'Defense',       img: '/badges/defense.png',       desc: 'Stop. Contest. Dominate.' },
  { name: 'IQ',            img: '/badges/iq.png',            desc: 'See more. Think faster. Win.' },
  { name: 'Ball Handling', img: '/badges/ball-handling.png', desc: 'Handles tight. Defenders lost.' },
  { name: 'Passing',       img: '/badges/passing.png',       desc: 'See it. Share it. Create.' },
  { name: 'Finishing',     img: '/badges/finishing.png',     desc: 'Strong finishes. No mercy.' },
  { name: 'Rebounding',    img: '/badges/rebounding.png',    desc: 'Own the glass. Own the game.' },
]

// 3 fully-fleshed sample profiles + 5 roster placeholders
export const PLAYERS = {
  'brolen-hill': {
    id: 'brolen-hill',
    name: 'Brolen Hill',
    jersey: '24',
    classOf: 'Class of 2032',
    grade: '7th',
    age: 12,
    ageGroup: '12u',
    position: 'Point Guard',
    height: '5’10”',
    weight: '132 lb',
    wingspan: '5’10”',
    vertical: '26”',
    handed: 'Right',
    archetype: '',
    nickname: '"Cold-Blooded K9 Sniper"',
    hometown: 'Springfield, MO',
    accolades: ['2× National Champion', '2× State Champion', '3× Regional Champion', '3× Regional MVP', '#2 Nationally'],
    photos: [
      { label: 'PORTRAIT',    sub: '// COACH-FACING',      aspect: '3/4', src: '/players/brolen/portrait.png' },
      { label: 'GAME ACTION', sub: '// OPEN-COURT DRIVE',  aspect: '4/5', src: '/players/brolen/action-1.jpg' },
      { label: 'GAME ACTION', sub: '// DOWNHILL · NCHBC',  aspect: '1/1', src: '/players/brolen/action-2.jpg' },
    ],
    stats: {
      season: '2025–26',
      ppg: '17.7', rpg: '6.1', apg: '3.7', spg: '1.9', bpg: '0.4',
      fg: '41.2%', three: '33%', ft: '79.0%',
      gp: '42',
    },
    careerHighs: [
      ['39', 'PTS',  'vs Greenfield'],
      ['13', 'REB',  'vs MHEA Eagles'],
      ['10', 'AST',  'vs Epps Elite'],
      ['9',  '3PM',  'vs KC East Lions'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 12U Regional MVP' },
      { y: '25–26', t: 'NCHBC 12U National Championship · National Runner-up' },
      { y: '25–26', t: 'NCHBC 14U · Finished 15th in the Nation' },
    ],
    academics: {
      gpa: '3.90', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '88th %ile',
      interests: 'Coding · Entrepreneurship · Gaming',
      references: ['Coach Dee Hamilton'],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'QTJKJYNG9wU', title: 'Brolen Hill · 12u Highlights · NCHBC 2025–26' },
    coachQuote: {
      text: 'Brolen’s got that dog in him — the bigger the moment, the more he wants it. His basketball IQ is off the charts, and when the game’s on the line, you want that three in his hands.',
      attr: 'Coach Dee Hamilton',
    },
    testimony: 'I want my teammates to score before I do. That’s the job.',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Brolen',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'jace-rucker': {
    id: 'jace-rucker',
    name: 'Jace Rucker',
    jersey: '0',
    classOf: 'Class of 2034',
    grade: '5th',
    age: 10,
    ageGroup: '10u',
    position: 'Point Guard',
    height: '5’2”',
    weight: '110 lb',
    wingspan: '5’5”',
    vertical: '18”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: 'Ozark, MO',
    accolades: ['State Champion', 'Regional Champion', '2026 Regional MVP', '#2 Nationally'],
    photos: [
      { label: 'PORTRAIT',    sub: '// COACH-FACING',    aspect: '3/4', src: '/players/jace-rucker/portrait.jpg' },
      { label: 'GAME ACTION', sub: '// RIM ATTACK',      aspect: '4/5', src: '/players/jace-rucker/action-1.jpg', fit: 'contain' },
      { label: 'GAME ACTION', sub: '// ON-BALL DEFENSE', aspect: '1/1', src: '/players/jace-rucker/action-2.jpg' },
    ],
    stats: {
      season: '2025–26',
      ppg: '19.3', rpg: '5.8', apg: '2.2', spg: '2.4', bpg: '1.8',
      fg: '37%', three: '31%', ft: '—',
      gp: '48',
    },
    careerHighs: [
      ['32', 'PTS',  'vs Bolivar'],
      ['9',  'REB',  'vs Strafford Indians'],
      ['6',  'AST',  'vs MHEA Eagles'],
      ['5',  '3PM',  'vs RUSH'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 10U Regional MVP' },
      { y: '25–26', t: 'NCHBC 12U National Championship · National Runner-up' },
    ],
    academics: {
      gpa: '4.0', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Sports Medicine',
      references: [],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'DLN8V7QktqQ', title: 'Jace Rucker · 10u Highlights · 2025–26' },
    coachQuote: {
      text: 'Jace is ten years old, starting on our 12u and winning — that tells you everything. The motor never stops. He hit five threes in the state championship game to help secure the victory. Ten years old.',
      attr: 'Coach Jason Hill',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Jace',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'javion-rucker': {
    id: 'javion-rucker',
    name: 'Javion Rucker',
    jersey: '5',
    classOf: 'Class of 2031',
    grade: '',
    age: '',
    ageGroup: '14u',
    position: 'Stretch Center',
    height: '5’9”',
    weight: '150 lb',
    wingspan: '5’10”',
    vertical: '21”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: ['State Champion', 'Regional Champion', '#2 Nationally'],
    photos: [
      { label: 'PORTRAIT',    sub: '// NCHBC NATIONALS', aspect: '3/4', src: '/players/javion-rucker/portrait.webp' },
      { label: 'GAME ACTION', sub: '// RISE & FINISH',   aspect: '4/5', src: '/players/javion-rucker/action-1.jpg' },
      { label: 'CHARACTER',   sub: '// CELEBRATION',     aspect: '1/1', src: '/players/javion-rucker/action-2.jpg' },
    ],
    stats: {
      season: '2025–26',
      ppg: '9.3', rpg: '7.9', apg: '1.1', spg: '1.6', bpg: '1.1',
      fg: '31%', three: '22%', ft: '—',
      gp: '45',
    },
    careerHighs: [
      ['24', 'PTS',  'vs Hoops Dream Elite'],
      ['18', 'REB',  'vs HDE'],
      ['4',  'AST',  'vs KC East Lions'],
      ['2',  '3PM',  'vs RUSH'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 12U National Championship · National Runner-up' },
    ],
    academics: {
      gpa: '4.0', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Coding · Entrepreneurship',
      references: [],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'rtqQooOQaE0', title: 'Javion · Highlights · 2025–26' },
    coachQuote: {
      text: 'Javion’s a dog. He sets the tone with his voice and his motor, and he’ll out-rebound guys bigger than him. He won’t let this group get quiet or comfortable.',
      attr: 'Coach Jason Hill',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Javion',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'tre-rucker': {
    id: 'tre-rucker',
    name: 'Tre Rucker',
    jersey: '1',
    classOf: 'Class of 2028',
    grade: '',
    age: '',
    ageGroup: '18u',
    position: 'Perimeter Big',
    height: '6’4”',
    weight: '207 lb',
    wingspan: '6’6”',
    vertical: '24”',
    handed: 'Left',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: [],
    photos: [
      { label: 'PORTRAIT',    sub: '// MEDALIST',   aspect: '3/4', src: '/players/tre-rucker/portrait.jpg' },
      { label: 'GAME ACTION', sub: '// RIM FINISH', aspect: '4/5', src: '/players/tre-rucker/action-1.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// BLOCK',      aspect: '1/1', src: '/players/tre-rucker/action-2.jpg', position: 'center' },
    ],
    stats: {
      season: '2025–26',
      ppg: '20.0', rpg: '10.0', apg: '7.0', spg: '1.1', bpg: '1.2',
      fg: '41.7%', three: '31.3%', ft: '71%',
      gp: '44',
    },
    careerHighs: [
      ['32', 'PTS',  'vs Lighthouse Chargers'],
      ['13', 'REB',  'vs Northwest Arkansas'],
      ['4',  'AST',  'vs Lebanon Rockets'],
      ['5',  '3PM',  'vs OKC Flame'],
    ],
    badges: ['Rebounding'],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: '#16 Nationally · 18U Team' },
    ],
    academics: {
      gpa: '4.0', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Entrepreneurship · Business',
      references: [],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'TrUtlYw1LBI', title: 'Tre Rucker · 18u Highlights · 2025–26' },
    coachQuote: {
      text: 'I call Tre “D1” — he’s got the body and the frame for it. It’s starting to come together for him now, and that should scare everyone. He’ll dunk on you one play and hit a step-back three the next. Watch out.',
      attr: 'Coach Jason Hill',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Tre',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'clay-dinsmore': {
    id: 'clay-dinsmore',
    name: 'Clay Dinsmore',
    jersey: '22',
    classOf: 'Class of 2030',
    grade: '',
    age: '',
    ageGroup: '16u',
    position: 'Shooting Guard',
    height: '6’0”',
    weight: '120 lb',
    wingspan: '6’2”',
    vertical: '24”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: [],
    photos: [
      { label: 'PORTRAIT',    sub: '// MEDALIST',  aspect: '3/4', src: '/players/clay-dinsmore/portrait.png' },
      { label: 'GAME ACTION', sub: '// JUMP SHOT', aspect: '4/5', src: '/players/clay-dinsmore/action-1.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// SCOOP',     aspect: '1/1', src: '/players/clay-dinsmore/action-2.jpg', position: 'center' },
    ],
    stats: {
      season: '2025–26',
      ppg: '9.8', rpg: '5.3', apg: '2.4', spg: '1.1', bpg: '0.9',
      fg: '42.2%', three: '40.1%', ft: '—',
      gp: '44',
    },
    careerHighs: [
      ['28', 'PTS',  'vs HillToppers · game-winning buzzer-beater in 3OT'],
      ['9',  'REB',  'vs OKC Flame'],
      ['7',  'AST',  'vs RUSH'],
      ['5',  '3PM',  'vs NWA'],
    ],
    badges: ['Christian Character', 'IQ', 'Ball Handling', 'Shooting'],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'Warriors Team MVP · 14U' },
    ],
    academics: {
      gpa: '3.8', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Music · Viola',
      otherInterests: ['Shows goats at livestock fairs', 'Cooking & baking', 'Volunteers with the elderly', 'Camping & zip-lining'],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'l5bmrK6ZcSA', title: 'Clay Dinsmore · 16u Highlights · 2025–26' },
    coachQuote: {
      text: 'Clay is long, agile, and plays whatever role we need that night — no ego. Best teammate you’ll find, always smiling, and one of the prettiest threes on the roster.',
      attr: 'Coach Dee Hamilton',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Clay',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'james-dinsmore': {
    id: 'james-dinsmore',
    name: 'James Dinsmore',
    jersey: '24',
    classOf: 'Class of 2029',
    grade: '',
    age: '',
    ageGroup: '18u',
    position: 'Point Guard',
    height: '6’0”',
    weight: '150 lb',
    wingspan: '5’11”',
    vertical: '25”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: [],
    photos: [
      { label: 'PORTRAIT',    sub: '// DRURY COURT',              aspect: '3/4', src: '/players/james-dinsmore/portrait.jpg' },
      { label: 'GAME ACTION', sub: '// AND1 · MEMPHIS GRIZZLIES', aspect: '4/5', src: '/players/james-dinsmore/action-1.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// FLOATER',                 aspect: '1/1', src: '/players/james-dinsmore/action-2.jpg', position: 'center' },
    ],
    stats: {
      season: '2025–26',
      ppg: '17.7', rpg: '4.1', apg: '3.3', spg: '1.3', bpg: '0.7',
      fg: '40.2%', three: '37.5%', ft: '—',
      gp: '48',
    },
    careerHighs: [
      ['30', 'PTS',  'vs HDE'],
      ['6',  'REB',  'vs NWA'],
      ['8',  'AST',  'vs Lighthouse Chargers'],
      ['7',  '3PM',  'vs Bradleyville'],
    ],
    badges: ['Christian Character', 'IQ', 'Ball Handling'],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 18U Regional MVP' },
      { y: '25–26', t: 'Warriors Team MVP · 18U' },
    ],
    academics: {
      gpa: '3.8', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Physical Science · Electrical · Starts college this fall',
      otherInterests: ['Plays guitar at music school', 'Youth worship team', 'Jr. Fire Cadet program', 'Shows goats at livestock fairs'],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'LVIockY5Thc', title: 'James Dinsmore · 18u Highlights · 2025–26' },
    coachQuote: {
      text: 'James is smooth. Earning all-region as a freshman is hard to do — most guys need years. He can stroke the three and he’s a true scorer.',
      attr: 'Coach Don Hamilton',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on James',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'cai-hamilton': {
    id: 'cai-hamilton',
    name: 'Cai Hamilton',
    jersey: '5',
    classOf: 'Class of 2030',
    grade: '',
    age: '',
    ageGroup: '16u',
    position: 'Point Guard',
    height: '5’8”',
    weight: '145 lb',
    wingspan: '5’9”',
    vertical: '26”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: [],
    photos: [
      { label: 'PORTRAIT',    sub: '// FORM',       aspect: '3/4', src: '/players/cai-hamilton/portrait.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// LAYUP',      aspect: '4/5', src: '/players/cai-hamilton/action-1.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// LOCKDOWN D', aspect: '1/1', src: '/players/cai-hamilton/action-2.jpg', position: 'center' },
    ],
    stats: {
      season: '2025–26',
      ppg: '8.9', rpg: '4.3', apg: '4.4', spg: '2.4', bpg: '0.7',
      fg: '39.4%', three: '34.9%', ft: '—',
      gp: '44',
    },
    careerHighs: [
      ['15', 'PTS',  'vs Lebanon Rockets'],
      ['9',  'REB',  'vs Lighthouse Chargers'],
      ['13', 'AST',  'vs KC East'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [],
    academics: {
      gpa: '—', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Music · Sports Business',
      otherInterests: ['Singing', 'Video editing'],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'cEoSwR22a70', title: 'Cai Hamilton · 16u Highlights · 2025–26' },
    coachQuote: {
      text: 'Cai has all the ability — super athletic, strong, our energy every night. When his mental game is on, he’s the captain of this team. That’s how much talent we’re talking about.',
      attr: 'Coach Jason Hill',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Cai',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'zane-hamilton': {
    id: 'zane-hamilton',
    name: 'Zane Hamilton',
    jersey: '3',
    classOf: 'Class of 2027',
    grade: '',
    age: '',
    ageGroup: '18u',
    position: 'Swiss Army Knife',
    height: '6’2”',
    weight: '155 lb',
    wingspan: '6’4”',
    vertical: '24”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: [],
    photos: [
      { label: 'PORTRAIT',    sub: '// INTRO',           aspect: '3/4', src: '/players/zane-hamilton/portrait.jpg' },
      { label: 'GAME ACTION', sub: '// FLOATER',         aspect: '4/5', src: '/players/zane-hamilton/action-1.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// MONSTER REBOUND', aspect: '1/1', src: '/players/zane-hamilton/action-2.jpg', position: 'center' },
    ],
    stats: {
      season: '2025–26',
      ppg: '6.2', rpg: '8.5', apg: '4.7', spg: '2.1', bpg: '1.5',
      fg: '40.1%', three: '31.3%', ft: '—',
      gp: '46',
    },
    careerHighs: [
      ['31', 'PTS',  'vs Chaos'],
      ['24', 'REB',  'vs Kings Elite'],
      ['13', 'AST',  'vs Lebanon Rockets'],
      ['5',  '3PM',  'vs Walnut Grove Tigers'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: '#31 Nationally · 18U Team' },
    ],
    academics: {
      gpa: '4.0', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Music Therapy · Computer Science',
      otherInterests: [],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'xR0MRDTXHBM', title: 'Zane Hamilton · Highlights · 2025–26' },
    coachQuote: {
      text: 'Zane is the heart and soul of our 18u — a triple-double threat every night. He’ll lock down their best player and drop eleven assists on the other end. Guards one through five. I love his game.',
      attr: 'Coach Jason Hill',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Zane',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'preston-bishop': {
    id: 'preston-bishop',
    name: 'Preston Bishop',
    jersey: '12',
    classOf: 'Class of 2031',
    grade: '',
    age: '',
    ageGroup: '14u',
    position: 'Point Guard',
    height: '5’9”',
    weight: '130 lb',
    wingspan: '5’9”',
    vertical: '24”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: ['Regional Champion', 'State Champion'],
    photos: [
      { label: 'PORTRAIT',    sub: '// RISE',       aspect: '3/4', src: '/players/preston-bishop/portrait-b.jpg', position: 'center' },
      { label: 'CHARACTER',   sub: '// HAND UP',    aspect: '4/5', src: '/players/preston-bishop/action-1.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// FAST BREAK', aspect: '1/1', src: '/players/preston-bishop/action-2.jpg', position: 'center' },
    ],
    stats: {
      season: '2025–26',
      ppg: '16.3', rpg: '6.1', apg: '3.2', spg: '3.2', bpg: '1.5',
      fg: '39.7%', three: '40.3%', ft: '—',
      gp: '44',
    },
    careerHighs: [
      ['44', 'PTS',  'vs Yanders Law'],
      ['11', 'REB',  'vs KC East Lions'],
      ['7',  'AST',  'vs Northwest Arkansas'],
      ['7',  '3PM',  'vs Yanders Law'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 12U National Championship · National Runner-up' },
    ],
    academics: {
      gpa: '3.8', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Civil Engineering · Business/Finance · Entrepreneurship',
      otherInterests: ['Fishing', 'Hunting'],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'dJ0stst9t9E', title: 'Preston · 14u Highlights · 2025–26' },
    coachQuote: {
      text: 'Preston’s got one speed: turbo. Most kids that fast lose control — he plays it at a high level. He’ll lock up your best guard and drop 40 on you.',
      attr: 'Coach Don Hamilton',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Preston',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'howard-zeigenbein': {
    id: 'howard-zeigenbein',
    name: 'Howard Zeigenbein',
    jersey: '24',
    classOf: 'Class of 2030',
    grade: '',
    age: '',
    ageGroup: '14u',
    position: 'Shooting Guard',
    height: '5’7”',
    weight: '117 lb',
    wingspan: '5’6”',
    vertical: '20”',
    handed: 'Ambidextrous',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: [],
    photos: [
      { label: 'PORTRAIT',    sub: '// WARRIOR 24',  aspect: '3/4', src: '/players/howard-zeigenbein/portrait.jpg', position: 'center' },
      { label: 'CHARACTER',   sub: '// WAW · GO 24',  aspect: '4/3', src: '/players/howard-zeigenbein/action-1.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// AT THE RIM',   aspect: '1/1', src: '/players/howard-zeigenbein/action-2.jpg', position: 'center' },
    ],
    stats: {
      season: '2025–26',
      ppg: '5.3', rpg: '2.9', apg: '1.7', spg: '0.9', bpg: '0.7',
      fg: '40.1%', three: '40.4%', ft: '—',
      gp: '18',
    },
    careerHighs: [
      ['16', 'PTS', 'vs Lebanon Rockets'],
      ['5',  'REB', 'vs Lighthouse Chargers'],
      ['6',  'AST', 'vs Bradleyville'],
      ['4',  '3PM', 'vs OKC Flame'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 14U · Finished 15th in the Nation' },
    ],
    academics: {
      gpa: '3.9', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Science · History',
      otherInterests: ['Baseball (SS · Pitcher · Catcher)', 'Fishing & making baits', 'Billiards', 'Piano', 'Clogging', 'Theater'],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { src: '', title: '' },
    coachQuote: {
      text: 'Howard joined us halfway through last season, still finding his rhythm. This summer he looks like a different player — comfortable, playing at a whole different speed. Scrappy, and he can score. Look out.',
      attr: 'Coach Dee Hamilton',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Howard',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'adonis-tennison': {
    id: 'adonis-tennison',
    name: 'Adonis Tennison',
    jersey: '1',
    classOf: 'Class of 2031',
    grade: '',
    age: '',
    ageGroup: '14u',
    position: 'Stretch Forward',
    height: '5’9”',
    weight: '127 lb',
    wingspan: '5’9”',
    vertical: '19”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: [],
    photos: [
      { label: 'PORTRAIT',    sub: '// WARRIOR',    aspect: '3/4', src: '/players/adonis-tennison/portrait.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// PULL-UP',    aspect: '4/5', src: '/players/adonis-tennison/action-1.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// ON THE GLASS', aspect: '3/4', src: '/players/adonis-tennison/action-2.jpg', position: 'center' },
    ],
    stats: {
      season: '2025–26',
      ppg: '5.8', rpg: '4.4', apg: '2.1', spg: '1.4', bpg: '0.7',
      fg: '38.8%', three: '35.5%', ft: '—',
      gp: '46',
    },
    careerHighs: [
      ['18', 'PTS', 'vs Bradleyville'],
      ['11', 'REB', 'vs NOAH Jaguars'],
      ['7',  'AST', 'vs HDE'],
      ['4',  '3PM', 'vs NWA'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 12U National Championship · National Runner-up' },
      { y: '25–26', t: 'NCHBC 14U · Finished 15th in the Nation' },
    ],
    academics: {
      gpa: '3.2', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Math · Debate · Business',
      otherInterests: ['Boxing', 'Fishing', 'Gaming'],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'fAeUvNr_VkQ', title: 'Adonis Tennison · Highlights · 2025–26' },
    coachQuote: {
      text: 'Adonis is the glue. He may not lead you in any one stat, but he does everything a winning team needs — boxes out, guards, moves it. Every champion has an Adonis.',
      attr: 'Coach Dee Hamilton',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Adonis',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'jojo-curtis': {
    id: 'jojo-curtis',
    name: 'JoJo Curtis',
    jersey: '54',
    classOf: 'Class of 2030',
    grade: '',
    age: '',
    ageGroup: '16u',
    position: 'Shooting Guard',
    height: '6’1”',
    weight: '141 lb',
    wingspan: '6’3”',
    vertical: '23”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: [],
    photos: [
      { label: 'PORTRAIT',    sub: '// PULL-UP',   aspect: '3/4', src: '/players/jojo-curtis/portrait.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// JUMPER',    aspect: '3/4', src: '/players/jojo-curtis/action-1.jpg', position: 'center' },
      { label: 'GAME ACTION', sub: '// FROM DEEP', aspect: '3/2', src: '/players/jojo-curtis/action-2.jpg', position: 'center' },
    ],
    stats: {
      season: '2025–26',
      ppg: '7.8', rpg: '7.1', apg: '3.3', spg: '2.1', bpg: '1.7',
      fg: '38.7%', three: '40.2%', ft: '—',
      gp: '48',
    },
    careerHighs: [
      ['20', 'PTS', 'vs RUSH'],
      ['11', 'REB', 'vs Lighthouse Chargers'],
      ['9',  'AST', 'vs Lebanon Rockets'],
      ['6',  '3PM', 'vs RUSH'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 14U · Finished 15th in the Nation' },
    ],
    academics: {
      gpa: '3.75', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Music · Piano',
      otherInterests: ['Tumbling', 'Photography'],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: {},
    coachQuote: {
      text: 'When JoJo’s locked into the game plan, he’s as dangerous as they come. He can shoot it, he can drive it, and he’s got a strong, grown basketball body. Focus is his superpower.',
      attr: 'Coach Don Hamilton',
    },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on JoJo',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'jordan-king': {
    id: 'jordan-king',
    name: 'Jordan King',
    jersey: '2',
    classOf: '',
    ageGroup: '12u',
    position: '',
    height: '',
    archetype: '',
    comingSoon: true,
    photos: [
      { label: 'PORTRAIT', sub: '// NEW WARRIOR', aspect: '3/4', src: '/players/jordan-king/portrait.jpg', position: 'center' },
    ],
  },

  'quincy-mboob': {
    id: 'quincy-mboob',
    name: 'Quincy Mboob',
    jersey: '11',
    classOf: '',
    ageGroup: '14u',
    position: '',
    height: '',
    archetype: '',
    comingSoon: true,
    photos: [
      { label: 'PORTRAIT', sub: '// NEW WARRIOR', aspect: '3/4', src: '/players/quincy-mboob/portrait.jpg', position: 'center' },
    ],
  },

  'diego-salazar': {
    id: 'diego-salazar',
    name: 'Diego Salazar',
    jersey: '15',
    classOf: 'Class of 2030',
    ageGroup: '14u',
    position: '',
    height: '',
    archetype: '',
    comingSoon: true,
    photos: [
      { label: 'PORTRAIT', sub: '// NEW WARRIOR', aspect: '3/4', src: '/players/diego-salazar/portrait.jpg', position: 'center' },
    ],
  },

  'barik-stalker': {
    id: 'barik-stalker',
    name: 'Barik Stalker',
    jersey: '13',
    classOf: '',
    ageGroup: '16u',
    position: '',
    height: '',
    archetype: '',
    comingSoon: true,
    photos: [
      { label: 'PORTRAIT', sub: '// NEW WARRIOR', aspect: '3/4', src: '/players/barik-stalker/portrait.jpg', position: 'center' },
    ],
  },
}

// ============================================================
// TEAMS — roster grouped by age group (boys); girls forming
// ============================================================

export const TEAMS = [
  {
    id: 'team-12u', short: '12U', label: 'Boys 12U', flagship: true,
    tag: '#2 Nationally', season: 'Heartland Regional Champions · 2025', coach: 'Coach Jason Hill',
    blurb: 'The flagship. Gold Ball champions and the #2-ranked 12U team in the country — in year one.',
    players: ['brolen-hill', 'jace-rucker', 'jordan-king'], openSpots: 2,
  },
  {
    id: 'team-10u', short: '10U', label: 'Boys 10U',
    tag: '', season: 'Season 2 · 2025–26', coach: 'Coach Dee Hamilton',
    blurb: 'Our youngest Warriors. Fundamentals, footwork, and the Badge Economy from day one.',
    players: ['jace-rucker'], openSpots: 4,
  },
  {
    id: 'team-14u', short: '14U', label: 'Boys 14U',
    tag: '', season: '2025–26', coach: 'Coach Jason Hill',
    blurb: 'The development engine — where shooters get built and recruiting profiles start to matter.',
    players: ['brolen-hill', 'javion-rucker', 'preston-bishop', 'howard-zeigenbein', 'adonis-tennison', 'quincy-mboob', 'diego-salazar'], openSpots: 1,
  },
  {
    id: 'team-16u', short: '16U', label: 'Boys 16U',
    tag: 'Roster forming', season: '2025–26', coach: 'Coach Dee Hamilton',
    blurb: 'College eyes start here. Every 16U Warrior carries a recruiting-ready profile.',
    players: ['clay-dinsmore', 'cai-hamilton', 'jojo-curtis', 'diego-salazar', 'barik-stalker'], openSpots: 4,
  },
  {
    id: 'team-18u', short: '18U', label: 'Boys 18U',
    tag: 'Recruiting class', season: '2025–26', coach: 'Coach Don Hamilton',
    blurb: 'Our oldest Warriors — the recruiting front line, with profiles built for college coaches.',
    players: ['tre-rucker', 'james-dinsmore', 'zane-hamilton', 'barik-stalker'], openSpots: 3,
  },
]
