// ============================================================
// THE WARRIORS — roster + profile data
// PLACEHOLDER seed data ported verbatim from the prototype
// (warriors.jsx). Jason replaces coaches / rosters / stats later.
// ============================================================

export const BADGES = [
  { name: 'Clutch Shooter',    glyph: '✦', desc: 'Written test on shot selection · on-court test for live-game shotmaking under pressure.' },
  { name: 'Lockdown Defender', glyph: '◆', desc: 'Closeouts, hip flips, switch IQ. Stops the best perimeter scorer on the scout.' },
  { name: 'Glass Dominator',   glyph: '⬢', desc: 'Boxing out, second-jump efficiency, contested rebounding in traffic.' },
  { name: 'Court Visionary',   glyph: '◈', desc: 'Pick-and-roll reads, second-side decisions, transition pace control.' },
]

// 3 fully-fleshed sample profiles + 5 roster placeholders
export const PLAYERS = {
  'eli-m': {
    id: 'eli-m',
    name: 'Eli M.',
    jersey: '14',
    classOf: 'Class of 2027',
    grade: '11th',
    age: 16,
    ageGroup: '17u',
    position: 'Wing',
    height: '6’4”',
    weight: '185 lb',
    wingspan: '6’8”',
    handed: 'Right',
    archetype: 'Two-way perimeter scorer',
    nickname: '"Two-Way"',
    hometown: 'Springfield, MO',
    photos: [
      { label: 'PORTRAIT',      sub: '// COACH-FACING HEADSHOT',  aspect: '3/4' },
      { label: 'GAME ACTION',   sub: '// PULL-UP MIDRANGE · HCHB', aspect: '4/5' },
      { label: 'CHARACTER',     sub: '// DEVOTION CIRCLE',         aspect: '1/1' },
    ],
    stats: {
      season: '2025–26',
      ppg: '21.1', rpg: '7.2', apg: '3.8', spg: '1.6', bpg: '0.9',
      fg: '52.4%', three: '38.1%', ft: '83.7%',
      gp: '38',
    },
    careerHighs: [
      ['41', 'PTS',  'vs Springfield Catholic · Jan 14, 2026'],
      ['12', 'REB',  'vs Iowa BIG · Mar 02, 2026'],
      ['8',  'AST',  'vs KS Premier · Feb 09, 2026'],
      ['6',  '3PM',  'vs Indiana Heat · Knightstown closer'],
    ],
    badges: ['Clutch Shooter', 'Lockdown Defender', 'Glass Dominator'],
    badgesInProgress: ['Court Visionary'],
    awards: [
      { y: '2026', t: 'NCHBC All-Tournament · Springfield' },
      { y: '2026', t: '3A All-State Honorable Mention' },
      { y: '2025', t: 'HCHB Final Four · 17u' },
    ],
    academics: {
      gpa: '4.10', gpaScale: 'weighted (4.0)',
      act: '28', sat: '—',
      iready: '92nd %ile',
      interests: 'Mechanical Engineering · Faith & Leadership',
      references: ['Coach Don Hamilton', 'Pastor R. Calloway', 'Mr. T. Reeves (Math)'],
    },
    socials: { hudl: 'hudl.com/eli-m', x: '@eli_m14', ig: '@eli.m.hoops' },
    highlight: { id: 'dQw4w9WgXcQ', title: 'Eli M. · Senior Season Mix · 2025–26' },
    coachQuote: {
      text: 'If we win the game, Eli probably guarded their best player. He doesn’t get sped up. He doesn’t need 25 shots. He just keeps making the right read.',
      attr: 'Coach Jason Hill · Director of Player Development',
    },
    testimony: 'Faith isn’t a halftime speech for me. It’s the reason I can lose a possession and still play the next one free.',
    contact: {
      name: 'Coach Don Hamilton',
      role: 'Athletic Director · Inquiries on Eli',
      email: 'recruiting@warriorsacademy.com',
      phone: '417 · — · ——',
    },
  },

  'jude-h': {
    id: 'jude-h',
    name: 'Jude H.',
    jersey: '03',
    classOf: 'Class of 2030',
    grade: '8th',
    age: 13,
    ageGroup: '14u',
    position: 'Shooting Guard',
    height: '6’1”',
    weight: '155 lb',
    wingspan: '6’3”',
    handed: 'Right',
    archetype: 'Movement shooter',
    nickname: '"The Knockdown"',
    hometown: 'Nixa, MO',
    photos: [
      { label: 'PORTRAIT',   sub: '// SHOP TEAM-GEAR FIT',     aspect: '3/4' },
      { label: 'JUMPER',     sub: '// RELEASE · DR. DISH BAY', aspect: '4/5' },
      { label: 'FAMILY',     sub: '// HCHB POST-GAME',         aspect: '1/1' },
    ],
    stats: {
      season: '2025–26',
      ppg: '18.4', rpg: '5.1', apg: '3.2', spg: '1.4', bpg: '0.3',
      fg: '49.1%', three: '41.0%', ft: '88.2%',
      gp: '42',
    },
    careerHighs: [
      ['34', 'PTS',  'vs Indiana Premier · Knightstown'],
      ['7',  '3PM',  'vs Wichita Storm · Mar 2026'],
      ['6',  'AST',  'vs Iowa Heat · Feb 2026'],
      ['9',  'REB',  'vs STL Eagles · Oct 2025'],
    ],
    badges: ['Clutch Shooter', 'Court Visionary'],
    badgesInProgress: ['Lockdown Defender'],
    awards: [
      { y: '2026', t: 'HCHB All-Tournament · 14u' },
      { y: '2025', t: 'NCHBC Springfield Selected' },
      { y: '2025', t: 'Warriors Most Improved · Year 1' },
    ],
    academics: {
      gpa: '3.85', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '90th %ile',
      interests: 'Coding · Sports Broadcasting',
      references: ['Coach Jason Hill', 'Coach Dee Hamilton'],
    },
    socials: { hudl: 'hudl.com/jude-h', x: '—', ig: '@jude.knockdown' },
    highlight: { id: 'dQw4w9WgXcQ', title: 'Jude H. · 14u Mid-Season Mix · 2025–26' },
    coachQuote: {
      text: 'He shoots it the same way at 6:45 in the morning on Dr. Dish as he does in the fourth quarter at NCHBC. That’s the whole point of Warriors.',
      attr: 'Coach Don Hamilton · Athletic Director',
    },
    testimony: 'My dad told me a shot doesn’t care if you’re tired. Practice gives you the right to not care either.',
    contact: {
      name: 'Coach Jason Hill',
      role: 'Director of Player Development · Inquiries on Jude',
      email: 'recruiting@warriorsacademy.com',
      phone: '417 · — · ——',
    },
  },

  'brolen-hill': {
    id: 'brolen-hill',
    name: 'Brolen Hill',
    jersey: '24',
    classOf: 'Class of 2032',
    grade: '7th',
    age: 12,
    ageGroup: '12u',
    position: 'Point Guard',
    height: '5’10”',
    weight: '132 lb',
    wingspan: '5’10”',
    vertical: '26”',
    handed: 'Right',
    archetype: '',
    nickname: '"Cold-Blooded K9 Sniper"',
    hometown: 'Springfield, MO',
    accolades: ['2× National Champion', '2× State Champion', '3× Regional Champion', '3× Regional MVP', '#2 Nationally'],
    photos: [
      { label: 'PORTRAIT',    sub: '// COACH-FACING',      aspect: '3/4', src: '/players/brolen/portrait.png' },
      { label: 'GAME ACTION', sub: '// OPEN-COURT DRIVE',  aspect: '4/5', src: '/players/brolen/action-1.jpg' },
      { label: 'GAME ACTION', sub: '// DOWNHILL · NCHBC',  aspect: '1/1', src: '/players/brolen/action-2.jpg' },
    ],
    stats: {
      season: '2025–26',
      ppg: '17.7', rpg: '6.1', apg: '3.7', spg: '1.9', bpg: '0.4',
      fg: '41.2%', three: '33%', ft: '79.0%',
      gp: '42',
    },
    careerHighs: [
      ['44', 'PTS',  'vs Springfield Lions'],
      ['13', 'REB',  'vs MHEA Eagles'],
      ['10', 'AST',  'vs Epps Elite'],
      ['9',  '3PM',  'vs KC East Lions'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 12U Regional MVP' },
      { y: '25–26', t: 'NCHBC 12U National Championship · National Runner-up' },
    ],
    academics: {
      gpa: '3.90', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '88th %ile',
      interests: 'Coding · Entrepreneurship · Gaming',
      references: ['Coach Dee Hamilton'],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { id: 'dQw4w9WgXcQ', title: 'Brolen Hill · 12u Highlights · NCHBC 2025–26' },
    coachQuote: {
      text: 'Brolen sees the play one beat ahead. Coachable. He’ll already be unselfish before he knows what unselfish is.',
      attr: 'Coach Dee Hamilton',
    },
    testimony: 'I want my teammates to score before I do. That’s the job.',
    contact: {
      name: 'Coach Jason Hill',
      role: '12u Head Coach · Inquiries on Brolen',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'jace-rucker': {
    id: 'jace-rucker',
    name: 'Jace Rucker',
    jersey: '0',
    classOf: 'Class of 2034',
    grade: '5th',
    age: 10,
    ageGroup: '10u',
    position: 'Point Guard',
    height: '5’2”',
    weight: '110 lb',
    wingspan: '5’5”',
    vertical: '18”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: 'Ozark, MO',
    accolades: ['State Champion', 'Regional Champion', '2026 Regional MVP', '#2 Nationally'],
    photos: [
      { label: 'PORTRAIT',    sub: '// COACH-FACING',    aspect: '3/4', src: '/players/jace-rucker/portrait.jpg' },
      { label: 'GAME ACTION', sub: '// RIM ATTACK',      aspect: '4/5', src: '/players/jace-rucker/action-1.jpg', fit: 'contain' },
      { label: 'GAME ACTION', sub: '// ON-BALL DEFENSE', aspect: '1/1', src: '/players/jace-rucker/action-2.jpg' },
    ],
    stats: {
      season: '2025–26',
      ppg: '19.3', rpg: '5.8', apg: '2.2', spg: '2.4', bpg: '1.8',
      fg: '37%', three: '31%', ft: '—',
      gp: '48',
    },
    careerHighs: [
      ['32', 'PTS',  'vs Bolivar'],
      ['9',  'REB',  'vs Strafford Indians'],
      ['6',  'AST',  'vs MHEA Eagles'],
      ['5',  '3PM',  'vs RUSH'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 10U Regional MVP' },
      { y: '25–26', t: 'NCHBC 10U National Championship · National Runner-up' },
    ],
    academics: {
      gpa: '4.0', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Sports Medicine',
      references: [],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { src: '/players/jace-rucker/highlight.mp4', title: 'Jace Rucker · 10u Highlights · 2025–26' },
    coachQuote: { text: '', attr: '' },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: '10u Head Coach · Inquiries on Jace',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },

  'javion-rucker': {
    id: 'javion-rucker',
    name: 'Javion Rucker',
    jersey: '5',
    classOf: 'Class of 2031',
    grade: '',
    age: '',
    ageGroup: '14u',
    position: 'Stretch Center',
    height: '5’9”',
    weight: '150 lb',
    wingspan: '5’10”',
    vertical: '21”',
    handed: 'Right',
    archetype: '',
    nickname: '',
    hometown: '',
    accolades: ['State Champion', 'Regional Champion', '#2 Nationally'],
    photos: [
      { label: 'PORTRAIT',    sub: '// NCHBC NATIONALS', aspect: '3/4', src: '/players/javion-rucker/portrait.png' },
      { label: 'GAME ACTION', sub: '// RISE & FINISH',   aspect: '4/5', src: '/players/javion-rucker/action-1.jpg' },
      { label: 'CHARACTER',   sub: '// CELEBRATION',     aspect: '1/1', src: '/players/javion-rucker/action-2.jpg' },
    ],
    stats: {
      season: '2025–26',
      ppg: '9.3', rpg: '7.9', apg: '1.1', spg: '1.6', bpg: '1.1',
      fg: '31%', three: '22%', ft: '—',
      gp: '45',
    },
    careerHighs: [
      ['24', 'PTS',  'vs Hoops Dream Elite'],
      ['18', 'REB',  'vs HDE'],
      ['4',  'AST',  'vs KC East Lions'],
      ['2',  '3PM',  'vs RUSH'],
    ],
    badges: [],
    badgesInProgress: [],
    awards: [
      { y: '25–26', t: 'NCHBC 14U National Championship · National Runner-up' },
    ],
    academics: {
      gpa: '4.0', gpaScale: 'unweighted (4.0)',
      act: '—', sat: '—',
      iready: '—',
      interests: 'Coding · Entrepreneurship',
      references: [],
    },
    socials: { hudl: '—', x: '—', ig: '—' },
    highlight: { src: '/players/javion-rucker/highlight.mp4', title: 'Javion · Highlights · 2025–26' },
    coachQuote: { text: '', attr: '' },
    testimony: '',
    contact: {
      name: 'Coach Jason Hill',
      role: '14u Head Coach · Inquiries on Javion',
      email: 'jason@mo-warriors.com',
      phone: '(417) 413-3305',
    },
  },
}

// ============================================================
// TEAMS — roster grouped by age group (boys); girls forming
// ============================================================

export const TEAMS = [
  {
    id: 'team-12u', short: '12U', label: 'Boys 12U', flagship: true,
    tag: '#2 Nationally', season: 'Heartland Regional Champions · 2025', coach: 'Coach Jason Hill',
    blurb: 'The flagship. Gold Ball champions and the #2-ranked 12U team in the country — in year one.',
    players: ['brolen-hill', 'jace-rucker'], openSpots: 2,
  },
  {
    id: 'team-10u', short: '10U', label: 'Boys 10U',
    tag: '#2 Nationally', season: 'Season 2 · 2025–26', coach: 'Coach Jason Hill',
    blurb: 'Our youngest Warriors. Fundamentals, footwork, and the Badge Economy from day one.',
    players: ['jace-rucker'], openSpots: 4,
  },
  {
    id: 'team-14u', short: '14U', label: 'Boys 14U',
    tag: 'HCHB All-Tournament', season: '2025–26', coach: 'Coach Jason Hill',
    blurb: 'The development engine — where shooters get built and recruiting profiles start to matter.',
    players: ['javion-rucker', 'jude-h'], openSpots: 3,
  },
  {
    id: 'team-16u', short: '16U', label: 'Boys 16U',
    tag: 'Roster forming', season: '2025–26', coach: 'Coach Don Hamilton',
    blurb: 'College eyes start here. Every 16U Warrior carries a recruiting-ready profile.',
    players: [], openSpots: 4,
  },
  {
    id: 'team-18u', short: '18U', label: 'Boys 18U',
    tag: 'Recruiting class', season: '2025–26', coach: 'Coach Don Hamilton',
    blurb: 'Our oldest Warriors — the recruiting front line, with profiles built for college coaches.',
    players: ['eli-m'], openSpots: 3,
  },
]
